# Generated by Django 3.2.7 on 2021-09-09 16:38

import django.core.validators
from django.db import migrations, models
import shortme.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000, verbose_name='Исходный адрес')),
                ('short_url_part', models.CharField(blank=True, db_index=True, error_messages={'max_length': 'Превышена длина ссылки в 20 символов!', 'unique': 'Такой адрес уже есть в базе. Выберите другой'}, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), shortme.utils.suitable_symbols_validator], verbose_name='Короткий адрес без домена')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('client_session', models.CharField(max_length=200, verbose_name='Идентификатор пользователя')),
            ],
        ),
    ]
