# Generated by Django 3.2.7 on 2021-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='client_session',
            field=models.CharField(max_length=1200, verbose_name='Идентификатор пользователя'),
        ),
    ]
